[project]
name = "fmb_tools"
version = "0.1.0"
description = "Flower Magic Ball (花花魔法球) - 給媽咪的小工具儲藏櫃"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]

[tool.uv]
dev-dependencies = [
    "nuitka>=2.4.11",
]
